
services:
  backend:
    build: /home/ubuntu/roamwise-backend
    container_name: roamwise-backend
    environment:
      DB_URL: jdbc:postgresql://roamwise.cvwuekisyde6.eu-north-1.rds.amazonaws.com:5432/roamwise
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: roamwise-z1vjbt.serverless.eun1.cache.amazonaws.com
      REDIS_PORT: "6379"
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_PLACES_KEY: ${GOOGLE_PLACES_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENWEATHERAPI_KEY: ${OPENWEATHERAPI_KEY}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      FRONTEND_URL: https://roamwise.live
      CORS_ALLOWED_ORIGINS: https://roamwise.live
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: /home/ubuntu/roamwise-frontend
    container_name: roamwise-frontend
    depends_on:
      - backend
    ports:
      - "4000:4000"
    environment:
      NG_ALLOWED_HOSTS: roamwise.live
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: roamwise-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

    depends_on:
      - frontend
      - backend

    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: